Modal Login
Orion-Constellation-Organization/Frontend pull request #1
Opened 2024-10-11 05:13 UTC by sarahaffonco

Criada modal e estilizada conforme prototipo.

2024-10-12 01:43 UTC, alanvrocha4 requested changes

2024-10-12 01:43 UTC, alanvrocha4 commented on src/app/home.component.ts
> +  title = 'Reforca-o-bem';
Não ta errado, mas é meio estranho tu olhar pro titulo de um site com `-` separando as palavras. Esse direcionamento estava na história, ou foi acertado com a PO ?

2024-10-12 01:43 UTC, alanvrocha4 commented on src/app/login/login.component.scss
> +$primary-color: #e1e1e3;
Essas variaveis são definições de tema, cria um arquivo theme.scss ou tu pode deixar ainda mais bem organizado criando um arquivo variables.scss e um theme.scss e estilos que são padrões por toda a aplicação, você coloca dentro de theme.scss, e as variaveis, tu coloca em variables.scss.

Aproveita e torne esses nomes de variaveis mais especificos, do tipo, $button-text-color, or $button-enable-text-color. o $hover-color, $button-hover-color ( depois tu pode ter cor de hover pra link, pra item de lista, e mais uma infinidade de elementos kkkk )

Faz o import desses 2 arquivos no arquivo style.scss pra pegar e ficar global

2024-10-12 01:43 UTC, alanvrocha4 commented on src/app/login/login.component.scss
> +    font-family: 'Open Sans', sans-serif;
Esses estilos de font-family estão seguindo certinho o figma ? Me causa estranheza 2 font-familys diferentes. Valida isso ;)

2024-10-12 01:43 UTC, alanvrocha4 commented on src/styles.scss
> +$primary-color: #e1e1e3;
você definiu essas variaveis aqui, e depois alterou no login.component.scss. o que vai acabar ficar valendo pra aplicação, vai ser o valor da variavel de lá.

primary, secondary e tertiary color, são cores default por toda a aplicação, se precisar que sejam alteradas, então o caso é criar novas variaveis para o elemente em especifico que você precisa. ;)

2024-10-14 23:22 UTC, sarahaffonco commented on src/app/home.component.ts
> +  title = 'Reforca-o-bem';
Foi desatenção. Corrigido

2024-10-14 23:35 UTC, sarahaffonco commented on src/app/login/login.component.scss
> +    font-family: 'Open Sans', sans-serif;
Sim, estou seguindo o figma

2024-10-16 01:02 UTC, alanvrocha4 commented on src/app/pages/login/login.component.html
> +    <div class="modal" @modal>
vou deixar passar nesse pr. No próximo, se houver distinção da forma como você e o Luis fazem modal, eu não vou aprovar nenhum dos dois enquanto não estiver no padrão hein ;)

2024-10-16 01:02 UTC, alanvrocha4 approved these changes

2024-10-16 01:03 UTC, merged