feature/tela-cadastro-aluno
Orion-Constellation-Organization/Frontend pull request #2
Opened 2024-10-11 13:02 UTC by Rigarlol

O link do trello com o card da task 
https://trello.com/c/S2nIfREz/64-oc-front-modal-cadastro-aluno

2024-10-12 01:59 UTC, alanvrocha4 requested changes
Importante, seu PR e da Sarah contém bastante pontos a serem alinhados entre vocês.

Por exemplo, tu usa angular material pro modal, sarah fez na mão. Alinhar como vão seguir com isso para padronizar.

Padronizar linguagem de urls, nome de componentes e de variaveis, e em qual idioma vocês vão escrever o código.

Legal alinharem também a estrutura para padronizar e começar a usar variaveis de tema para definir estilos padrões pela aplicação, diminui o trabalho conforme o projeto avança, e deixar tudo padronizado corretamente sem repetições de códigos e valores ;)

2024-10-12 01:59 UTC, alanvrocha4 commented on src/app/app-routing.module.ts
> +    path: 'cadastro-aluno',
Importante tu e a Sarah se alinharem, ela está usando urls em inglês, tu em português, conversem e definam um padrão, se não vai ficar uma sopinha de idiomas kkkkkk

2024-10-12 01:59 UTC, alanvrocha4 commented on src/app/app-routing.module.ts
> +    component: CadastroAlunoComponent
Nome dos componentes também, ela está usando em ingles, também alinhar isso.

2024-10-12 01:59 UTC, alanvrocha4 commented on src/app/pages/cadastro-aluno/cadastro-aluno.component.html
> +    <form class="formulario-container" [formGroup]="cadastroForm" (ngSubmit)="onSubmit()">
nome de formulário, nome de variavel do ts, em portugues, nome da função de submeter, em ingles. Conforme já pontuamos nos exercicios, manter padrão de nomenclatura pelo código.

Outro ponto, novamente, você e a Sarah precisam se alinhar em como vão seguir, ingles ou português

2024-10-12 01:59 UTC, alanvrocha4 commented on src/app/pages/cadastro-aluno/cadastro-aluno.component.html
> +            <input matInput formControlName="fullName" required />
Variavel em ingles, formulário nomeado em pt-br

2024-10-12 01:59 UTC, alanvrocha4 commented on src/app/pages/cadastro-aluno/cadastro-aluno.component.html
> +            <input matInput formControlName="username" required />
Variavel em ingles, formulário nomeado em pt-br 

Revise o arquivo após alinhamento, tem bastante repetição dos mesmo problemas ;)

2024-10-12 01:59 UTC, alanvrocha4 commented on src/app/pages/cadastro-aluno/cadastro-aluno.component.ts
> +      const cadastroData = {
Esses nomes dos campos estão alinhado com o backend ?

2024-10-14 23:41 UTC, Rigarlol commented
Realizei as alterações pedidas no código

2024-10-15 01:18 UTC, alanvrocha4 commented on src/app/pages/student-registration-form/student-registration-form.component.ts
> +  educationLevels = ['Fundamental', 'Ensino Médio', 'Pré Vestibular'];
Pelo que eu entendi, isso aqui vai vir do backend né ? Depois vai precisar refatorar pra pegar o endpoint de lá e renderizar aqui

2024-10-15 01:22 UTC, alanvrocha4 requested changes

2024-10-15 01:22 UTC, alanvrocha4 commented on src/app/pages/student-registration-form/student-registration-form.component.ts
> +    this.fechar.emit();
variavel em pt-br aqui ainda.

2024-10-15 01:57 UTC, Rigarlol commented on src/app/pages/student-registration-form/student-registration-form.component.ts
> +  educationLevels = ['Fundamental', 'Ensino Médio', 'Pré Vestibular'];
Isso mesmo, é que tem uma task justamente pra integrar com o backend depois

2024-10-16 01:03 UTC, alanvrocha4 approved these changes

2024-10-23 00:43 UTC, closed without merging